author: Ricardo SIGNES <rjbs@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Mail-Audit-PGP
no_index: 
  directory: 
    - inc
    - t
requires: 
  Mail::Audit: 2.217
version: 1.701
